---
paths:
  /api/v1/user:
    get:
      tags:
        - User
      summary: Get all users
      responses:
        '200':
          description: Completed successfully
    post:
      tags:
        - User
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                pwd:
                  type: string
      responses:
        '200':
          description: Completed successfully
  /api/v1/user/{user_id}:
    get:
      tags:
        - User
      summary: Get user by ID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Completed successfully
    delete:
      tags:
        - User
      summary: Delete user by ID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Completed successfully
    put:
      tags:
        - User
      summary: Update user by ID
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                pwd:
                  type: string
      responses:
        '200':
          description: Completed successfully
  /api/v1/skill:
    get:
      tags:
        - Skill
      summary: Get all skills
      responses:
        '200':
          description: Completed successfully
    post:
      tags:
        - Skill
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                skill:
                  type: string
                description:
                  type: string
                user_id:
                  type: string
      responses:
        '200':
          description: Completed successfully
  /api/v1/skill/{skill_id}:
    get:
      tags:
        - Skill
      summary: Get user by ID
      parameters:
        - name: skill_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Completed successfully
    delete:
      tags:
        - Skill
      summary: Delete user by ID
      parameters:
        - name: skill_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Completed successfully
    put:
      tags:
        - Skill
      summary: Update user by ID
      parameters:
        - name: skill_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                skill:
                  type: string
                description:
                  type: string
                user_id:
                  type: string
      responses:
        '200':
          description: Completed successfully
